=== Jhon-Salazar386/TheDigitalQuest/HTML/Ciudades.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="CodigoType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nombreType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ubicacionType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="ciudades">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ciudad" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="nombreType"></xs:element>
                            <xs:element name="ubicacion" type="ubicacionType"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="CodigoType" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jhon-Salazar386/TheDigitalQuest/XML,XSD, XSLT(Jhon)/Ciudades.xml
<?xml version="1.0" encoding="UTF-8"?>
<ciudades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ciudades.xsd">
    <ciudad codigo="MAD">
        <nombre>Madrid</nombre>
        <ubicacion>Centro de España</ubicacion>
    </ciudad>

    <ciudad codigo="BCN">
        <nombre>Barcelona</nombre>
        <ubicacion>Nordeste de España, costa mediterránea</ubicacion>
    </ciudad>

    <ciudad codigo="VAL">
        <nombre>Valencia</nombre>
        <ubicacion>Este de España, costa mediterránea</ubicacion>
    </ciudad>

    <ciudad codigo="SEV">
        <nombre>Sevilla</nombre>
        <ubicacion>Sur de España, región de Andalucía</ubicacion>
    </ciudad>

    <ciudad codigo="BIL">
        <nombre>Bilbao</nombre>
        <ubicacion>Norte de España, País Vasco</ubicacion>
    </ciudad>
</ciudades>
