=== Jhon-Salazar386/TheDigitalQuest/XML,XSD, XSLT(Jhon)/Deportistas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="DniType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{8}[A-Z]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NombreType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ApellidoType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GeneroType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Hombre"/>
            <xs:enumeration value="Mujer"/>
            <xs:enumeration value="Otros"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="EdadType">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="18"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="CiudadnacType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="lista">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="deportista" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="NombreType"></xs:element>
                            <xs:element name="apellido" type="ApellidoType"></xs:element>
                            <xs:element name="genero" type="GeneroType"></xs:element>
                            <xs:element name="edad" type="EdadType"></xs:element>
                            <xs:element name="ciudadNac" type="CiudadnacType" minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="dni" type="DniType" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jhon-Salazar386/TheDigitalQuest/XML,XSD, XSLT(Jhon)/Deportistas.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Deportistas.xsd">

    <deportista dni="12345678A">
        <nombre>Pablo</nombre>
        <apellido>García</apellido>
        <genero>Hombre</genero>
        <edad>20</edad>
        <ciudadNac>Madrid</ciudadNac>
    </deportista>

    <deportista dni="87654321B">
        <nombre>Carlos</nombre>
        <apellido>Martínez</apellido>
        <genero>Hombre</genero>
        <edad>27</edad>
        <ciudadNac>Barcelona</ciudadNac>
    </deportista>

    <deportista dni="23456789C">
        <nombre>Ana</nombre>
        <apellido>Hernández</apellido>
        <genero>Mujer</genero>
        <edad>19</edad>
        <ciudadNac>Valencia</ciudadNac>
    </deportista>

    <deportista dni="98765432D">
        <nombre>Javier</nombre>
        <apellido>Ruiz</apellido>
        <genero>Mujer</genero>
        <edad>31</edad>
        <ciudadNac>Sevilla</ciudadNac>
    </deportista>

    <deportista dni="34567890E">
        <nombre>María</nombre>
        <apellido>Lopez</apellido>
        <genero>Mujer</genero>
        <edad>24</edad>
        <ciudadNac>Bilbao</ciudadNac>
    </deportista>

</lista>
